steps:	
# Build the container image	
- name: 'gcr.io/cloud-builders/docker'	
  args: ['build', '-t', 'gcr.io/gcp-practice-302000/toscan', '.']	
# Push the container image to Container Registry	
- name: 'gcr.io/cloud-builders/docker'	
  args: ['push', 'gcr.io/gcp-practice-302000/toscan']	
# Deploy container image to Cloud Run	
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'	
  entrypoint: gcloud	
  args: ['run', 'deploy', 'toscan','--region', 'us-central1', '--image', 'gcr.io/gcp-practice-302000/toscan', '--platform', 'managed','--port','80']	
images:	
  - gcr.io/gcp-practice-302000/toscan 